apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 'jenkins'
  description: 'a description'
  annotations:
    jenkins.io/job-full-name: "test-jenkins-org" # use this instead

spec:
  type: service
  lifecycle: experimental
  owner: DaggupatiPavan
